import type { CategoryId, DeckManifest } from "@ask-me-more/contracts";

export type SeededDeck = {
  categoryId: CategoryId;
  questions: string[];
};

export const deckManifest: DeckManifest = {
  version: "2026.04.18",
  generatedAt: new Date().toISOString(),
  categories: [
    {
      id: "discovery",
      label: "Self Discovery",
      description: "Explore who you truly are",
      iconKey: "star",
      accentColor: "#7B4F8E",
      backgroundColor: "#F4EDF8",
      accessLevel: "free",
      totalQuestions: 24,
    },
    {
      id: "dreams",
      label: "Dreams & Goals",
      description: "Share your visions for the future",
      iconKey: "target",
      accentColor: "#2B6A8B",
      backgroundColor: "#E8F3F9",
      accessLevel: "free",
      totalQuestions: 18,
    },
    {
      id: "playful",
      label: "Playful & Fun",
      description: "Light-hearted conversation starters",
      iconKey: "sun",
      accentColor: "#B86B15",
      backgroundColor: "#FEF3E4",
      accessLevel: "free",
      totalQuestions: 30,
    },
    {
      id: "deeper",
      label: "Going Deeper",
      description: "Questions that reveal your soul",
      iconKey: "layers",
      accentColor: "#8B2020",
      backgroundColor: "#FDECEA",
      accessLevel: "free",
      totalQuestions: 22,
    },
    {
      id: "values",
      label: "Core Values",
      description: "What truly matters to you both",
      iconKey: "shield",
      accentColor: "#1F7A4B",
      backgroundColor: "#E8F6EE",
      accessLevel: "free",
      totalQuestions: 16,
    },
    {
      id: "intimacy",
      label: "Intimacy & Love",
      description: "Deepen your emotional connection",
      iconKey: "heart",
      accentColor: "#8B2252",
      backgroundColor: "#FCE8F1",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "childhood",
      label: "Childhood & Family",
      description: "Explore roots and family dynamics",
      iconKey: "home",
      accentColor: "#4A6B5D",
      backgroundColor: "#EBF3F0",
      accessLevel: "free",
      totalQuestions: 25,
    },
    {
      id: "fears",
      label: "Fears & Insecurities",
      description: "Vulnerable conversations about fears",
      iconKey: "cloud-rain",
      accentColor: "#545454",
      backgroundColor: "#F0F0F0",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "spiritual",
      label: "Spiritual & Philosophical",
      description: "Deep dives into existence and the universe",
      iconKey: "moon",
      accentColor: "#3F3A60",
      backgroundColor: "#EBEAF2",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "whatifs",
      label: "What Ifs",
      description: "Fun, thought-provoking hypothetical scenarios",
      iconKey: "help-circle",
      accentColor: "#D96C06",
      backgroundColor: "#FDF0E3",
      accessLevel: "free",
      totalQuestions: 30,
    },
    {
      id: "popculture",
      label: "Pop Culture",
      description: "Movies, music, and entertainment debates",
      iconKey: "tv",
      accentColor: "#B52B65",
      backgroundColor: "#F9EAF0",
      accessLevel: "free",
      totalQuestions: 25,
    },
    {
      id: "money",
      label: "Money & Finances",
      description: "Values around wealth, spending, and saving",
      iconKey: "dollar-sign",
      accentColor: "#2A7B4C",
      backgroundColor: "#EAF3ED",
      accessLevel: "free",
      totalQuestions: 18,
    },
    {
      id: "travel",
      label: "Travel & Adventure",
      description: "Bucket lists, wanderlust, and past trips",
      iconKey: "map",
      accentColor: "#0F7B8C",
      backgroundColor: "#E5F4F6",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "friendships",
      label: "Friendships",
      description: "Navigating platonic relationships",
      iconKey: "users",
      accentColor: "#6A3F9A",
      backgroundColor: "#F1EBF7",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "nostalgia",
      label: "Nostalgia",
      description: "Fond memories and looking back",
      iconKey: "camera",
      accentColor: "#A65A28",
      backgroundColor: "#FAF0EA",
      accessLevel: "free",
      totalQuestions: 22,
    },
    {
      id: "conflict",
      label: "Conflict & Growth",
      description: "How we fight, resolve, and grow",
      iconKey: "zap",
      accentColor: "#C92A2A",
      backgroundColor: "#FCEAEA",
      accessLevel: "free",
      totalQuestions: 24,
    },
    {
      id: "work",
      label: "Work & Ambition",
      description: "Career goals, burnout, and professional drive",
      iconKey: "briefcase",
      accentColor: "#1B4965",
      backgroundColor: "#E6EDF2",
      accessLevel: "free",
      totalQuestions: 20,
    },
    {
      id: "spicy",
      label: "Spicy",
      description: "Intimate and provocative questions",
      iconKey: "flame",
      accentColor: "#D62828",
      backgroundColor: "#FBEAEA",
      accessLevel: "free",
      totalQuestions: 25,
    }
  ],
  quotes: [
    {
      text: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
      author: "Marcel Proust",
    },
    {
      text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
      author: "Lao Tzu",
    },
    {
      text: "You do not love someone for their looks, or their clothes. You love them because they sing a song only you can hear.",
      author: "Oscar Wilde",
    },
  ],
};

export const seededDecks: SeededDeck[] = [
  {
    categoryId: "discovery",
    questions: [
      "What moment from your childhood shaped who you are most deeply, and how do you still carry it today?",
      "If you could relive one perfectly ordinary day of your life exactly as it was, which day would you choose and why?",
      "What is one belief you once held firmly that you have since completely let go of, and what changed your mind?",
      "Describe a version of yourself you have grown away from. Is there anything you still quietly miss about them?",
      "What is something about yourself that took you the longest to truly accept?",
    ],
  },
  {
    categoryId: "dreams",
    questions: [
      "Where do you picture yourself in ten years, not career-wise, but emotionally and personally?",
      "Is there a dream you have quietly set aside that still resurfaces when you are alone with your thoughts?",
      "What kind of home environment do you dream of, and what feeling would it give you walking through the door?",
      "If money and practicality were no concern, how would you spend every Tuesday afternoon for the rest of your life?",
      "What is one adventure you have always imagined us taking together someday, but have not said out loud yet?",
    ],
  },
  {
    categoryId: "playful",
    questions: [
      "If our relationship were a movie, what genre would it be and who would you cast to play each of us?",
      "What is one completely irrational food opinion you will passionately defend for the rest of your life?",
      "If you could instantly become an expert in any one skill just to impress me, what would you choose?",
      "What is the most embarrassing thing you have Googled in the past month that you would actually admit to?",
      "If we had our own reality show, what would it be called and what would the cameras mostly catch us doing?",
    ],
  },
  {
    categoryId: "deeper",
    questions: [
      "Is there something you have never said out loud that you have been quietly carrying for a long time?",
      "What does home truly mean to you: a place, a feeling, or a specific person?",
      "When do you feel most alone, even when you are surrounded by people who care about you?",
      "What is a version of yourself you are still slowly becoming, and what is standing in the way?",
      "What do you wish people understood about you that they almost never seem to?",
    ],
  },
  {
    categoryId: "values",
    questions: [
      "What is one principle you would never compromise on, regardless of the cost or consequence?",
      "How do you define success today, and has that shifted since we have been together?",
      "What does loyalty actually look like in practice to you, beyond just the word itself?",
      "What human quality do you think is the most underrated in the world today?",
      "What does fairness mean to you in a relationship, and do you think we genuinely live it?",
    ],
  },
  {
    categoryId: "intimacy",
    questions: [
      "When do you feel most deeply loved by me, and what does that moment usually look like?",
      "Is there a way I could better show up for you that you have been a little hesitant to ask for?",
      "What is something small I do that means far more to you than I probably realize?",
      "What feeling do you most want to experience more of in our relationship going forward?",
      "When you imagine us together 30 years from now, what is the one thing you hope stays exactly the same?",
    ],
  },
  {
    categoryId: "childhood",
    questions: [
      "What is a smell that instantly brings you back to a specific moment in your childhood?",
      "What was the most unspoken rule in your household growing up?",
      "Which family member do you think you are secretly most similar to, even if you wouldn't admit it?",
      "What is something your parents did that you promised yourself you would never do?",
      "What was your favorite place to hide or escape to when you were a kid?",
    ],
  },
  {
    categoryId: "fears",
    questions: [
      "What is an irrational fear you have that you know makes absolutely no sense?",
      "What is the most terrifying thing you have ever done completely voluntarily?",
      "Is there a fear you have about our relationship that you hesitate to bring up?",
      "What is something you are afraid you will never have the chance to do?",
      "How does your body physically react when you are truly scared of failing at something?",
    ],
  },
  {
    categoryId: "spiritual",
    questions: [
      "Have you ever had an experience that you truly could not explain logically?",
      "What do you think happens to our consciousness when we die?",
      "Do you believe in soulmates, or do you think we just choose to make it work with someone?",
      "What makes you feel most connected to something larger than yourself?",
      "If you could ask the universe one question and get a guaranteed true answer, what would you ask?",
    ],
  },
  {
    categoryId: "whatifs",
    questions: [
      "If you had to live the rest of your life in a fictional universe, which one would you choose?",
      "What if you woke up tomorrow and had to leave your current life behind, where would you go?",
      "If you could pause time for exactly one hour every day, what would you do with that hour?",
      "What if you could read minds, but only when people were thinking about you. Would you want that power?",
      "If we had met 10 years earlier, do you think we would have ended up together?",
    ],
  },
  {
    categoryId: "popculture",
    questions: [
      "Which movie completely changes its meaning when you watch it for the second time?",
      "What is a piece of pop culture (movie, song, game) that you pretend to like so you don't feel left out?",
      "If you could live inside a music video, which one would it be and why?",
      "Which TV show character is most like you, in the most embarrassing way possible?",
      "What celebrity death actually genuinely affected you?",
    ],
  },
  {
    categoryId: "money",
    questions: [
      "If you won a massive lottery, what is the very first entirely selfish thing you would buy?",
      "How did your parents talk about money when you were growing up, and how did that affect you?",
      "What is a purchase you made that you deeply regret to this day?",
      "Do you think money can actually buy happiness, up to a certain point?",
      "What is something you spend a ridiculous amount of money on that you refuse to compromise on?",
    ],
  },
  {
    categoryId: "travel",
    questions: [
      "What is the most profoundly beautiful place you have ever seen with your own eyes?",
      "If we could teleport anywhere in the world for just 24 hours right now, where would we go?",
      "What is the worst travel experience you have ever had that you can laugh about now?",
      "Do you prefer a tightly planned itinerary or wandering with absolutely no plan?",
      "Where is a place you want to travel to strictly because of the food?",
    ],
  },
  {
    categoryId: "friendships",
    questions: [
      "Have you ever had a friendship breakup that hurt more than a romantic one?",
      "What is a trait you look for in a friend now that you didn't care about 5 years ago?",
      "Who is the one friend you know would drop everything to help you in an emergency?",
      "Do you think it's possible to maintain a truly platonic friendship with someone you were once attracted to?",
      "What makes you immediately distance yourself from a new friend?",
    ],
  },
  {
    categoryId: "nostalgia",
    questions: [
      "What is a song that instantly transports you back to high school?",
      "What was your absolute favorite toy or possession when you were a kid?",
      "Do you have a memory that you aren't actually sure is real, or if you just dreamed it?",
      "What is a trend from the past that you desperately wish would come back?",
      "Who was your very first crush and what made you like them?",
    ],
  },
  {
    categoryId: "conflict",
    questions: [
      "What is your default defense mechanism when you feel criticized?",
      "Have you ever held a grudge for years, only to realize later you were in the wrong?",
      "What is the most trivial thing we have ever had a serious argument about?",
      "How do you need to be comforted after a really bad fight?",
      "What is something I do during an argument that makes it impossible for you to stay mad?",
    ],
  },
  {
    categoryId: "work",
    questions: [
      "If every job in the world paid exactly the same amount, what would you choose to do for a living?",
      "What was your very first job, and what did it teach you about the real world?",
      "Do you work to live, or live to work?",
      "Have you ever experienced severe burnout, and how did you finally get out of it?",
      "What is a skill you use every day at work that you wish you didn't have to use?",
    ],
  },
  {
    categoryId: "spicy",
    questions: [
      "What is something you find incredibly attractive that is not traditionally considered 'sexy'?",
      "Have you ever been surprised by something you actually enjoyed in bed?",
      "What is a fantasy you have always had but never had the chance to act out?",
      "When was the exact moment you first felt a physical spark between us?",
      "What is your absolute favorite physical feature of mine?",
    ],
  }
];

export const seededDeckMap = Object.fromEntries(
  seededDecks.map((deck) => [deck.categoryId, deck.questions]),
) as Record<CategoryId, string[]>;
